version: "3.8"
networks:
    default:
        name: data-labeling-network
        external: true
services:
    data-label-cli:
        image: data-label-cli
        container_name: data-label-cli
        volumes:
            - ../../secrets:/secrets
            - ../data-labeling-cli:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /secrets/data-service-account.json
            GCP_PROJECT: "ads-chat"
            GCP_ZONE: "us-central1-a"
            GCS_BUCKET_NAME: "ads-chat-data"
            LABEL_STUDIO_URL: "http://data-label-studio:8080"
        depends_on:
            - data-label-studio
    data-label-studio:
        image: heartexlabs/label-studio:latest
        container_name: data-label-studio
        ports:
            - 80:8080 # map port 80 on the host to port 8080 in the container
        volumes:
            - ./docker-volumes/label-studio:/label-studio/data
            - ../../secrets:/secrets
        environment:
            LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK: "true"
            LABEL_STUDIO_USERNAME: "admin@admin.com"
            LABEL_STUDIO_PASSWORD: "awesome"
            GOOGLE_APPLICATION_CREDENTIALS: /secrets/data-service-account.json
            GCP_PROJECT: "ads-chat-data"
            GCP_ZONE: "us-central1-a"
